language: node_js

node_js:
  - '11'

cache:
  - npm: true
  - yarn: true

matrix:
  fast_finish: true

install:
  - npm install -g codecov
  - yarn install

before_script:
  - export NODE_OPTIONS="--max-old-space-size=8192"
  - yarn build

script:
  - yarn test

after_script:
  - codecov
